import SidebarLayout from "@/components/sidebar-layout/sidebar-layout";
import { superAdminSidebarMenuItems } from "@/lib/config/super-admin-menu-items";
import { requireAuth } from "@/lib/require-auth";
import { Role } from "@/lib/types";
import type { Metadata } from "next";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default async function SuperAdminRootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    const user = await requireAuth({ role: Role.SUPER_ADMIN });

    return (
        <SidebarLayout user={user}>
            {children}
        </SidebarLayout>
    );
}
