import type { Metadata } from "next";
import { Geist, Geist_Mono, Public_Sans } from "next/font/google";
import "../globals.css";
import { ThemeProvider } from "@/context/theme-provider";
import { Toaster } from "@/components/ui/sonner";
import { redirect } from "next/navigation";
import { AuthProvider } from "@/context/auth-provider";
import { getSession } from "@/lib/get-session";
import ReactQueryClientProvider from "@/lib/react-query/queryClientProvider";
import { cookies } from "next/headers";
import { CookieKey } from "@/lib/constants";

const publicSans = Public_Sans({ subsets: ['latin'], variable: '--font-sans' });

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default async function ProtectedRootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    const user = await getSession();

    if (!user) redirect('/auth/sign-in');

    const cookieStore = await cookies();
    const token = cookieStore.get(CookieKey.ACCESS_TOKEN)?.value || "";

    return (
        <html lang="en" className={publicSans.variable}>
            <body
                className={`${geistSans.variable} ${geistMono.variable} antialiased`}
            >
                <ReactQueryClientProvider>
                    <AuthProvider initialUser={user} initialAccessToken={token}>
                        <ThemeProvider
                            attribute="class"
                            defaultTheme="dark"
                            enableSystem
                            disableTransitionOnChange
                        >
                            {children}
                            <Toaster richColors />
                        </ThemeProvider>
                    </AuthProvider>
                </ReactQueryClientProvider>
            </body>
        </html>
    );
}
